import { StyleSheet } from 'react-native';

const CardStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f7f7',
  },
  newsFeedContainer: {
    marginTop: 17,
    paddingHorizontal: 15,
  },
  topBox: {
    width: '100%',
    height: 120, 
    backgroundColor: '#9f00ff',
    position: 'relative', 
    justifyContent: 'center', 
    alignItems: 'center', 
    overflow: 'hidden', 
  },
  title: {
    position: 'absolute',
    fontSize: 32,
    textAlign: 'left',
    top: '6%',
    left: 20,
    padding: 10,
    color: '#fff',
    fontFamily: 'BebasNeue-Regular',
  },
  vector: {
    position: 'absolute',
    top: '10%',
    width: '130%',
    height: '130%',
    opacity: 0.2,
    left: '10%',
  },
  notificationIconContainer: {
    position: 'absolute',
    top:'7.5%', 
    right: 25, 
    zIndex: 10, 
  },
  notificationIcon: {
    width: 32,  
    height: 32, 
    tintColor: '#fff', 
  },
  notificationBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#ff0000', 
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  notificationCount: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  postCard: {
    backgroundColor: '#fff',
    marginBottom: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
    paddingBottom: 0,
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  profileImage: {
    width: 50,
    height: 50,
    borderRadius: 45,
    marginRight: 15,
    borderWidth: 2,
    borderColor: '#fff',
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  postImage: {
    width: '100%',
    height: 280,
  },
  caption: {
    fontSize: 22,
    fontWeight: '600',
    color: '#333',
    padding: 15,
    marginTop: 10,
  },
  postDescription: {
    fontSize: 16,
    color: '#777',
    lineHeight: 22,
    paddingHorizontal: 15,
    paddingBottom: 15,
    fontStyle: 'italic',
  },
  interactionContainer: {
    flexDirection: 'row',
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  interactionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#f5f5f5',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    marginRight: 15,
  },
  interactionIcon: {
    width: 24,
    height: 24,
    tintColor: '#888',
    marginRight: 5,
  },
  likeText: {
    fontSize: 16,
    color: '#888',
    fontWeight: '500',
  },
  commentsSection: {
    paddingHorizontal: 15,
    paddingBottom: 15,
    backgroundColor: '#f9f9f9',
    marginTop: 10,
    borderRadius: 10,
  },
  comment: {
    marginBottom: 10,
  },
  commentText: {
    fontSize: 14,
    color: '#777',
  },
  commentUserName: {
    fontWeight: 'bold',
    color: '#333',
  },
  commentInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    paddingTop: 10,
  },
  commentInput: {
    height: 40,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 25,
    flex: 1,
    paddingLeft: 15,
    fontSize: 14,
    color: '#333',
  },
  submitButton: {
    padding: 10,
  },
  submitButtonIcon: {
    width: 30,
    height: 30,
    tintColor: '#9f00ff',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',  
  },
  modalContainer: {
    width: '85%',
    padding: 25,
    backgroundColor: '#fff',
    borderRadius: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
    textAlign: 'left',
  },
  modalMessage: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#9f00ff', 
    borderRadius: 50,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,  
  },
  closeButtonIcon: {
    width: 20,
    height: 20,
    tintColor: '#fff', 
  },
  backgroundDots: {
    opacity: 0.15,
    tintColor: '#fff',
    width: 500,
    height: 300,
    right: 10,
  }
});

export default CardStyle;
