// MatchesStyles.tsx
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F3F3FF',
  },
  title: {
    position: 'absolute',
    fontSize: 32,
    textAlign: 'left',
    top: '6%',
    left: 20,
    padding: 10,
    color: '#fff',
    fontFamily: 'BebasNeue-Regular',
  },
  subtitle: {
    marginTop: 20,
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    fontFamily: 'Manrope-Regular',
    opacity: 0.6,
  },
  topBox: {
    width: '200%',
    height: 120,
    backgroundColor: '#9f00ff',
    position: 'absolute',
    top: 0,
    left: 0,
    overflow: 'hidden',
  },
  vector: {
    position: 'absolute',
    top: '0%',
    width: '120%',
    height: '120%',
    opacity: 0.2,
    left: '-25%',
  },
  tabContainer: {
    marginTop: 140,
    flexDirection: 'row',
    justifyContent: 'flex-start', 
    paddingHorizontal: 20, 
  },
  tab: {
    marginRight: 40, 
    paddingVertical: 10,
  },
  tabText: {
    fontSize: 22,
    color: '#555',
    fontFamily: 'BebasNeue-Regular',
  },
  activeTabText: {
    color: '#9f00ff',
    fontFamily: 'BebasNeue-Regular',
  },
  underline: {
    position: 'absolute',
    bottom: 0,
    height: 2.25,
    width: 100, 
    backgroundColor: '#9f00ff',
    borderRadius: 5,
  },
  card: {
    top: '-7%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 15,
    marginTop: 75,
    width: '90%',
    height: '15%',
    borderWidth: 1,
    borderColor: '#E7E4E4FF',
    backgroundColor: '#EDEDED',
    alignSelf: 'center', 
    borderRadius: 8, 
    position: 'relative', 
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  cardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  cardRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    position: 'relative', 
  },
  logoContainer: {
    width: 45,
    height: 45,
    marginRight: 10,
  },
  logo: {
    width: '125%',
    height: '125%',
  },
  clubText: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 24,
    color: '#333',
  },
  time: {
    position: 'absolute',
    top: -35,
    right: 5,
    fontSize: 16,
    color: '#000',
    fontFamily: 'Manrope-Regular',
  },
  topBoxInfo: {
    position: 'absolute',
    top: -30, 
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  leagueMatch: {
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#000',
    backgroundColor: '#fff',
    padding: 5,
    borderRadius: 4,
    marginBottom: 5,
  },
  cardBackground: {
    flex: 1,
  },
  cardImage: {
    height: 185,
    width: '109%',
    left: -15,
    top: -45,
    resizeMode: 'cover',
  },
  matchDayInfo: {
    position: 'absolute',
    bottom: 10, 
    left: 15,
    width: '90%',
    paddingHorizontal: 10,
  },
  matchDay: {
    position: 'absolute',
    fontFamily: 'Manrope-Regular',
    fontSize: 16,
    color: '#fff',
    marginTop: 68,
    left: 200,
  },
  stadium: {
    position: 'absolute',
    fontFamily: 'Manrope-Regular',
    fontSize: 17,
    color: '#fff',
    marginTop: 66,
    left: -6,
  },
  date: {
    position: 'absolute',
    fontFamily: 'Manrope-Regular',
    fontSize: 14,
    color: '#000',
    marginTop: -67,
    left: -9,
  },
  arrowImage: {
    position: 'absolute',
    bottom: -93,  
    right: -15,   
    width: 45,   
    height: 45,  
  },
  backgroundDots: {
    opacity: 0.15,
    tintColor: '#fff',
    width: 300,
    height: 300,
    right: 50,
  }
});

export default styles;
